# # see: https://terraform-docs.io/user-guide/configuration/version
# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: main.tf

# see: https://terraform-docs.io/user-guide/configuration/footer-from
# footer-from: footer.md

# see: https://terraform-docs.io/user-guide/configuration/recursive
recursive:
  enabled: false
  path: modules

# see: https://terraform-docs.io/user-guide/configuration/sections
